import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import Navbar from "./_components/Navbar"; // adjust path as needed
import '../node_modules/@fortawesome/fontawesome-free/css/all.min.css'

import "./globals.css";
import Footer from "./_components/Footer";
import { Toaster } from "react-hot-toast";
import { NextAuthProviders } from "@/providers/next-auth-providers";

const encode = Encode_Sans({
 weight: ["400", "500"],

  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${encode.className}`}
      >
        <Toaster/>
        
         <div className="flex flex-col justify-around min-h-screen">
        <NextAuthProviders>
       
    <Navbar></Navbar>
        <div className="container max-w-[1400px]">
 {children}
 
        </div>
</NextAuthProviders>
        </div>
        
   <Footer></Footer>
       
      </body>
    </html>
  );
}
